import { QuestionType, Step, StepType } from "../types";

export const steps: Step[] = [
  {
    title: "Welcome to Medly!",
    description:
      "Just **7 quick questions** before we can get started with your first lesson for free.",
    primaryButtonText: "Get started!",
  },
  {
    title: "Let's create your profile",
    type: StepType.QUESTION,
    description: "",
    questions: [
      {
        fieldName: "userName",
        title: "What should we call you?",
        type: QuestionType.TEXT,
        placeholder: "Your Nickname",
      },
      {
        fieldName: "avatar",
        title: "Choose your avatar",
        type: QuestionType.AVATAR,
        options: [
          "🦊",
          "🐼",
          "🐔",
          "🦄",
          "🦋",
          "🦁",
          "🐙",
          "🦦",
          "🦥",
          "🧸",
          "🐭",
          "🐰",
        ],
        values: [
          "🦊",
          "🐼",
          "🐔",
          "🦄",
          "🦋",
          "🦁",
          "🐙",
          "🦦",
          "🦥",
          "🧸",
          "🐭",
          "🐰",
        ],
      },
    ],
    primaryButtonText: "Continue",
    shouldCountInProgressBar: true,
  },
  {
    title: "What brings you to Medly?",
    type: StepType.QUESTION,
    questions: [
      {
        fieldName: "focusArea",
        type: QuestionType.MULTIPLE_CHOICE,
        options: [
          "Reducing exam stress",
          "To get ahead",
          "Maximising grades",
          "I need help to pass",
          "Revision resources all in one place",
          "Personal tutoring at an affordable cost",
        ],
        values: [
          "Reducing exam stress",
          "To get ahead",
          "Maximising grades",
          "I need help to pass",
          "Revision resources all in one place",
          "Personal tutoring at an affordable cost",
        ],
      },
    ],
    primaryButtonText: "Continue",
    shouldCountInProgressBar: true,
  },
  {
    title: "How did you hear about Medly?",
    type: StepType.QUESTION,
    questions: [
      {
        fieldName: "source",
        type: QuestionType.MULTIPLE_CHOICE,
        options: [
          "Snapchat",
          "Google Search",
          "Facebook/Instagram",
          "Friends/family",
          "TikTok",
          "Reddit",
          "Teacher",
          "Mumsnet",
          "The Student Room",
        ],
        values: [
          "Snapchat",
          "Google Search",
          "Facebook/Instagram",
          "Friends/family",
          "TikTok",
          "Reddit",
          "Teacher",
          "Mumsnet",
          "The Student Room",
        ],
      },
    ],
    primaryButtonText: "Continue",
    shouldCountInProgressBar: true,
  },
  {
    title: "What year are you in?",
    type: StepType.QUESTION,
    questions: [
      {
        fieldName: "year",
        type: QuestionType.MULTIPLE_CHOICE,
        options: ["Year 9", "Year 10", "Year 11", "Year 12", "Year 13"],
        values: [9, 10, 11, 12, 13],
      },
    ],
    primaryButtonText: "Continue",
    shouldCountInProgressBar: true,
  },
  {
    title: "One quick step!",
    hint: "Since you're under 18, please share your parent or guardian's email. We won't share your grades without asking you first.",
    questions: [
      {
        fieldName: "parentEmail",
        type: QuestionType.TEXT,
        placeholder: "Parent/Guardian email",
      },
    ],
    primaryButtonText: "Continue",
    shouldCountInProgressBar: true,
  },
  {
    title: "What subjects are you studying?",
    hint: "You can change these later.",
    type: StepType.SUBJECTS,
    shouldCountInProgressBar: true,
  },
  // {
  //   title: "Your 2026 exam dates",
  //   type: StepType.EXAM_DATES,
  //   primaryButtonText: "Confirm dates",
  //   secondaryButtonText: "Skip for now",
  //   shouldCountInProgressBar: true,
  // },
  {
    title: "Want to know the secret to acing your {course}s?",
    primaryButtonText: "I'm interested!",
  },
  {
    title: "The secret to acing your exams is to",
    type: StepType.SECRETS,
    primaryButtonText: "Continue",
  },
  {
    title: "It's hard doing this on your own!",
    type: StepType.SECRETS_FADED,
    primaryButtonText: "Continue",
  },
  {
    title: "So Medly will guide you every step of the way!",
    type: StepType.SECRETS_MEDLY,
    primaryButtonText: "Continue",
  },
];
