/**
 * Type exports for Open Platform schema
 *
 * These provide convenient type aliases for insert/select operations.
 * Tables are generated by `npm run db:introspect` into ./migrations/schema.ts
 */
import {
  openPlatformChatThread,
  openPlatformCollection,
  openPlatformDocument,
  openPlatformFolder,
  openPlatformUser,
} from "./migrations/schema";

export type OpenPlatformUser = typeof openPlatformUser.$inferSelect;
export type NewOpenPlatformUser = typeof openPlatformUser.$inferInsert;

export type OpenPlatformCollection = typeof openPlatformCollection.$inferSelect;
export type NewOpenPlatformCollection =
  typeof openPlatformCollection.$inferInsert;

export type OpenPlatformFolder = typeof openPlatformFolder.$inferSelect;
export type NewOpenPlatformFolder = typeof openPlatformFolder.$inferInsert;

export type OpenPlatformDocument = typeof openPlatformDocument.$inferSelect;
export type NewOpenPlatformDocument = typeof openPlatformDocument.$inferInsert;

export type OpenPlatformChatThread = typeof openPlatformChatThread.$inferSelect;
export type NewOpenPlatformChatThread =
  typeof openPlatformChatThread.$inferInsert;
